# Main Bot Configuration File

# activity_type Options:
# -1 - Unknown
# 0 - Playing
# 1 - Streaming
# 2 - Listening
# 3 - Watching
# 4 & 5 seem to not work. Feel free to try. (Custom and Competing respectively.)

bot_name: "DeveloperJoe"
bug_report_channel: null
status_type: 2
status_text: "/help and answering lifes biggest questions."
default_gpt_model: "gpt-3.5-turbo"

# Voice Configuration

listening_keyword: "assistant"
listening_timeout: 2.5
voice_speedup_multiplier: 1.17
allow_voice: true

# Region Settings (Global)

timezone: "UTC"
