import datetime

DEBUG = True
QUERY_TIMEOUT = 10
QUERY_CONFIRMATION = ">y"

GPT_MODAL = "gpt-4-32k"
OPENAI_API_KEY = "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"
STREAM_UPDATE_MESSAGE_FREQUENCY = 10
CHARACTER_LIMIT = 2000
VERSION = "1.2"

TIMEZONE = datetime.timezone.utc